"Secret": "AKIAIOSFODNN7EXAMPLE"
"aws_secret_access_key": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
"aws_session_token": "AQoDYXdzEJr//////////wEa4EXAMPLEtc2VjA0b3JpZ2luYWwvdGVzdC9leGFtcGxlL3Rlc3QtZGF0YS9leGFtcGxlLXRlc3QtZGF0YS5qc29uCg=="